### ISSUE TITLE
Example for Shiny Core

### ISSUE THREAD

**Issue by Rebekah-Chuang** [eodaGmbH/py-tabulator#23]
Thanks for this awesome package, I was looking for the pagination feature in shiny python.
I'm wondering if there's any basic usage example for `Shiny Core`, thanks!

**Comment by crazycapivara** [comment]
@Rebekah-Chuang Just added a `Shiny core` example to the [docs](https://eodagmbh.github.io/py-tabulator/).

Basically in Shiny core you additionally need to add the output func `output_tabulator` to your UI:

```python
app_ui = ui.page_fluid(
    output_tabulator("tabulator"),
)


def server(input, output, session):
    @render_tabulator
    def tabulator():
        df = pd.read_csv(
            "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
        )
        return Tabulator(df, table_options=TableOptions(height=311))
```

**Comment by Rebekah-Chuang** [comment]
@crazycapivara , Thanks for adding it!
