### ISSUE TITLE
how to save edited table

### ISSUE THREAD

**Issue by j0bekt01** [eodaGmbH/py-tabulator#28]
I have been spinning my wheels trying to save the edited table as a new data frame. Is it possible to do that whit a shiny core? the examples are limited and don't have that option. BTW, this is something rather easy with R DT.

**Comment by crazycapivara** [comment]
Hi @j0bekt01 Maybe it was a little bit hidden in the main example.

So, I added a new example [here](https://eodagmbh.github.io/py-tabulator/examples/edit_data/).

**Comment by j0bekt01** [comment]
> Hi @j0bekt01 Maybe it was a little bit hidden in the main example.
> 
> So, I added a new example [here](https://eodagmbh.github.io/py-tabulator/examples/edit_data/).
I did eventually get it to work. I appreciate the prompt response.
