### ISSUE TITLE
Table headers

### ISSUE THREAD

**Issue by j0bekt01** [eodaGmbH/py-tabulator#30]
How would you use a column value as a table header? 
something like this:
![image](https://github.com/eodaGmbH/py-tabulator/assets/10472277/1d5f5511-f6b2-46ad-8be0-679573de5845)

**Comment by crazycapivara** [comment]
@j0bekt01 I am not not completely sure if I got. Do you mean something like this https://tabulator.info/examples/6.2#responsive-layout-collapse. ANother option would be using [grouping](https://tabulator.info/examples/6.2#grouping).

**Comment by j0bekt01** [comment]
I've found an alternate solution.
