### ISSUE TITLE
Documentation unavailable

### ISSUE THREAD

**Issue by yreynaud** [eodaGmbH/py-tabulator#38]
Trying to have an eye on the documentation, it seems that it isn't available right now (whereas last week it was accessible). Here is what appears when we click on the documentation link:
![image](https://github.com/user-attachments/assets/6e02f526-df71-40ac-84db-60d188199c10)

**Comment by crazycapivara** [comment]
Hi @yreynaud 
it moved to [here](https://eoda-dev.github.io/py-tabulator/) because we moved from eoda-gmbh to eoda-dev :-)

**Comment by yreynaud** [comment]
Hello @crazycapivara 
Thanks for your quick answer. Il should be a good idea to update the link given in the README of the repo :)

**Comment by crazycapivara** [comment]
@yreynaud Thanx, now fixed.
