### ISSUE TITLE
Pandas version requirement

### ISSUE THREAD

**Issue by wch** [eodaGmbH/py-tabulator#8]
I wasn't sure where to ask this question so I thought I'd file an issue.

Does py-tabulator require features from Pandas 2.2.0, or could it also work with older versions like 1.5.3? The reason I ask is because Pyodide ships with 1.5.3, and Shinylive is built on Pyodide. It would be great if the example could work in a shinylive.io link [like this](https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMASxlWICcyACVKCAEygGcXe2nADoQAZo2Iw22MlABGAVwA2UMkxZ0GzFgBV5SuAHlUZGqR54WjSpziMA+t1n3xsOCPGSWPABY0I2Br0TKzWXHYeElK+-tgYcAAeqNY8fJohGhCoCmSWCjQi6do4xJw0tpFeZkFarADKZIz+AOYAkoYiIvkYZQBuABRCYADCSjSEANYspFbEAO4samxN5CzQ8EOWPGTYBgC8Q+ycZRDNiCwAjAAMqAkA3EMAlJ0QIgACYbaMGCQV0DzYCCEFi2USLBJkfqPRAiFhw5b+SH+bJkDCyRQqNQOCRzeyEMaTOCcKHPCDwqxwMgKRhk5E5NHyZSqJj2HF4gkTIlQ4BDABybiGAF0Xu9PnZHKooC5GG5+uiDPZiCYzBAeHs9HIDMZTOZ+j44DRmj4yHsAKxXK6PUmgxaMzFMKEwsnwwg8Xr2CgQlh7FjNSn2alKQbO8lwobGsioHiIAD0MZlcwwzRoZB8CkUPDsJHIlFRJBgMacvEINEohCJxAAVsRC5LM2QeDGYLwKIwY6ZZBBxj83UNYfDSeTrFSaYIMNYoJw8W7+g0Vm1DP1Xe7PWQrSLTv7A97pKVynAfqUD4wFBB7JWeMHyX2wH2Qyx+oHHt6AHwsED98nZ7YUgCOCjgH8fQgOAFgADQAWQAGQACTISMACU4H-QDIUeB57zhawUO2DAlUoQYwAAcQAUR0TYWEDSxRCgJRM3Qlg4xYGi6LgZj1ABIEfAkCBiAUPhsIA7ZP3hQTUIwTMuH6CBlCUdCRLhGgwX6MTcO2VR+O9PYfQAJgtZ8P0w0Nh2pMlVNRFIGFVOAdESMgMNDFgAF8WDgVj3wU4zKVMlgbwc0MnJEwL7xvO9STAJy8HAdYEGQQSaGseByB4NEIXwIhSAoKhkBwdEmSxCLBSAA).

**Comment by crazycapivara** [comment]
@wch I just set the version for pandas to 1.5.3, but now we got the problem with Pydantic. Pyodide ships with 1.10.2, but I need >= 2.0. There are some breaking changes form 1 to 2. Maybe I can make pydantic optional and use `dataclass` for the table options as fallback. It is still included, because this was used in the first pre-release.

**Comment by crazycapivara** [comment]
@wch I made Pydantic optional and now with the latest version it works in Shinylive :-)

**Comment by crazycapivara** [comment]
@wch If this works for you aswell, I would close this issue.

**Comment by wch** [comment]
Great, thank you!
